example-app/routes/web.php
<?php

use App\Http\Controllers\Admin\BillController;
use App\Http\Controllers\Admin\ClassifyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MotorbikeController;
use App\Http\Controllers\Admin\OrderbikeController;
use App\Models\Classifybike;
use App\Models\Customer;

use App\Http\Controllers\Admin\Motorbikeontroller;
use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard')
->middleware('auth');





// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('roles', RoleController::class);

Route::get('/motorbikes/search', [MotorbikeController::class,'search'])->name('motorbikes.search');
Route::resource('motorbikes', MotorbikeController::class)->middleware('auth');






Route::get('/classify/search', [ClassifyController::class,'search'])->name('classify.search');
Route::resource('classify',ClassifyController::class)->middleware('auth');



// Route::get('customers/create', CustomerController::class, 'create')->name('customers.create');






Auth::routes();







// // Route::resource('orderbikes',OrderbikeController::class);
// //search
// Route::get('/orderbikes/search', [OrderbikeController::class,'search'])->name('orderbikes.search');

// //orderbike
// Route::get('/orderbikes',[OrderbikeController::class, 'index'])
// ->name('orderbikes.index');



// // create orderbike
// Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])
// ->name('orderbikes.create');
// Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])
// ->name('orderbikes.store');
// //show
// Route::get('orderbikes/{id}', [OrderbikeController::class,'show'])
// ->name('orderbikes.show');

// //edit orderbike
// Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])
// ->name('orderbikes.edit');
// Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])
// ->name('orderbikes.update');

// //delete
// Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])
// ->name('orderbikes.destroy');


Route::middleware('auth')->group(function () {
    // Search Orderbikes
    Route::get('/orderbikes/search', [OrderbikeController::class, 'search'])->name('orderbikes.search');

    // Show Orderbikes
    Route::get('/orderbikes', [OrderbikeController::class, 'index'])->name('orderbikes.index');

    // Create Orderbike
    Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])->name('orderbikes.create');
    Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])->name('orderbikes.store');

    // Show Orderbike details
    Route::get('/orderbikes/{id}', [OrderbikeController::class, 'show'])->name('orderbikes.show');

    // Edit Orderbike
    Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])->name('orderbikes.edit');
    Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])->name('orderbikes.update');

    // Delete Orderbike
    Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])->name('orderbikes.destroy');
});





// //customers
// Route::get('/customers',[CustomerController::class, 'index'])
// ->name('customers.index');

// // create customers
// Route::get('/customers/create', [CustomerController::class, 'create'])
// ->name('customers.create');
// Route::post('/customers/store', [CustomerController::class, 'store'])
// ->name('customers.store');

// //edit customers
// Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])
// ->name('customers.edit');
// Route::put('/customers/update/{id}', [CustomerController::class, 'update'])
// ->name('customers.update');

// //delete
// Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])
// ->name('customers.destroy');

// //search
// Route::get('/customers/search', [CustomerController::class,'search'])->name('customers.search');


// Route::post('/customers/store-ajax', [CustomerController::class,'storeAjax'])->name('customers.storeAjax');

Route::middleware('auth')->group(function () {
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers/store', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/update/{id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])->name('customers.destroy');
    Route::get('/customers/search', [CustomerController::class, 'search'])->name('customers.search');
    Route::post('/customers/store-ajax', [CustomerController::class, 'storeAjax'])->name('customers.storeAjax');
});









Route::get('/bills/search', [BillController::class,'search'])->name('bills.search');

Route::resource('bills', BillController::class)->middleware('auth');
Route::post('/bills/store', [BillController::class, 'store'])
->name('bills.store')->middleware('auth');

example-app/resources/views/admin/layouts/sidebar.blade.php
<aside
    class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
    id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
            aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="{{ route('dashboard') }}">
            <img src="https://static.vecteezy.com/system/resources/previews/009/117/067/non_2x/ddn-logo-ddn-letter-ddn-letter-logo-design-initials-ddn-logo-linked-with-circle-and-uppercase-monogram-logo-ddn-typography-for-technology-business-and-real-estate-brand-vector.jpg" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">DDN Motorbike Rental</span> <br>
            {{-- <span class="ms-1 font-weight-bold text-white">Hello: {{ auth()->user()->name }}</span> --}}
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('dashboard') ? 'bg-gradient-info active' : ''}}" href="{{ route('dashboard') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">dashboard</i>
                    </div>
                    <span class="nav-link-text ms-1">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('motorbikes.*') ? 'bg-gradient-info active' : ''}} " href="{{ route('motorbikes.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">motorcycle</i>
                    </div>
                    <span class="nav-link-text ms-1">Motorbike</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('customers.*') ? 'bg-gradient-info active' : ''}} " href="{{ route('customers.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">person</i>
                    </div>
                    <span class="nav-link-text ms-1">Customer</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('classify.*') ? 'bg-gradient-info active' : ''}} " href="{{route('classify.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">view_in_ar</i>
                    </div>
                    <span class="nav-link-text ms-1">Classify</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('orderbikes.*')  ? 'bg-gradient-info active' : ''}} " href="{{ route('orderbikes.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">handshake</i>
                    </div>
                    <span class="nav-link-text ms-1">Orderbikes</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('bills.*')  ? 'bg-gradient-info active' : ''}}" href="{{ route('bills.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">local_grocery_store</i>
                    </div>
                    <span class="nav-link-text ms-1">Bills</span>
                </a>
            </li>

        </ul>
    </div>
</aside>