example-app/routes/web.php
<?php

use App\Http\Controllers\Admin\BillController;
use App\Http\Controllers\Admin\ClassifyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MotorbikeController;
use App\Http\Controllers\Admin\OrderbikeController;
use App\Models\Classifybike;
use App\Models\Customer;

use App\Http\Controllers\Admin\Motorbikeontroller;
use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard')
->middleware('auth');





// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('roles', RoleController::class);

Route::get('/motorbikes/search', [MotorbikeController::class,'search'])->name('motorbikes.search');
Route::resource('motorbikes', MotorbikeController::class)->middleware('auth');






Route::get('/classify/search', [ClassifyController::class,'search'])->name('classify.search');
Route::resource('classify',ClassifyController::class)->middleware('auth');



// Route::get('customers/create', CustomerController::class, 'create')->name('customers.create');






Auth::routes();







// // Route::resource('orderbikes',OrderbikeController::class);
// //search
// Route::get('/orderbikes/search', [OrderbikeController::class,'search'])->name('orderbikes.search');

// //orderbike
// Route::get('/orderbikes',[OrderbikeController::class, 'index'])
// ->name('orderbikes.index');



// // create orderbike
// Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])
// ->name('orderbikes.create');
// Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])
// ->name('orderbikes.store');
// //show
// Route::get('orderbikes/{id}', [OrderbikeController::class,'show'])
// ->name('orderbikes.show');

// //edit orderbike
// Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])
// ->name('orderbikes.edit');
// Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])
// ->name('orderbikes.update');

// //delete
// Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])
// ->name('orderbikes.destroy');


Route::middleware('auth')->group(function () {
    // Search Orderbikes
    Route::get('/orderbikes/search', [OrderbikeController::class, 'search'])->name('orderbikes.search');

    // Show Orderbikes
    Route::get('/orderbikes', [OrderbikeController::class, 'index'])->name('orderbikes.index');

    // Create Orderbike
    Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])->name('orderbikes.create');
    Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])->name('orderbikes.store');

    // Show Orderbike details
    Route::get('/orderbikes/{id}', [OrderbikeController::class, 'show'])->name('orderbikes.show');

    // Edit Orderbike
    Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])->name('orderbikes.edit');
    Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])->name('orderbikes.update');

    // Delete Orderbike
    Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])->name('orderbikes.destroy');
});





// //customers
// Route::get('/customers',[CustomerController::class, 'index'])
// ->name('customers.index');

// // create customers
// Route::get('/customers/create', [CustomerController::class, 'create'])
// ->name('customers.create');
// Route::post('/customers/store', [CustomerController::class, 'store'])
// ->name('customers.store');

// //edit customers
// Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])
// ->name('customers.edit');
// Route::put('/customers/update/{id}', [CustomerController::class, 'update'])
// ->name('customers.update');

// //delete
// Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])
// ->name('customers.destroy');

// //search
// Route::get('/customers/search', [CustomerController::class,'search'])->name('customers.search');


// Route::post('/customers/store-ajax', [CustomerController::class,'storeAjax'])->name('customers.storeAjax');

Route::middleware('auth')->group(function () {
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers/store', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/update/{id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])->name('customers.destroy');
    Route::get('/customers/search', [CustomerController::class, 'search'])->name('customers.search');
    Route::post('/customers/store-ajax', [CustomerController::class, 'storeAjax'])->name('customers.storeAjax');
});









Route::get('/bills/search', [BillController::class,'search'])->name('bills.search');

Route::resource('bills', BillController::class)->middleware('auth');
Route::post('/bills/store', [BillController::class, 'store'])
->name('bills.store')->middleware('auth');

example-app/app/Models/Motorbike.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Motorbike extends Model
{
    use HasFactory;

    protected $fillable = [
        'tenxe',
        'hangxe',
        'bienso',
        'giathue',
        'status',
        'classifybike_id',
        'image'
    ];


    public function classify(){
        return $this->belongsTo(Classifybike::class,'classifybike_id','id');
    }

}

example-app/app/Http/Controllers/Admin/MotorbikeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Motorbike\CreateMotorbikeRequest;
use App\Http\Requests\Motorbike\UpdateMotorbikeRequest;
use App\Models\Classifybike;
use App\Models\Motorbike;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class MotorbikeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        $motorbikes = Motorbike::with('classify')->paginate(10);
        return view('admin.motorbikes.index', compact('motorbikes'));
    }
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $classifys = Classifybike::all();
        return view('admin.motorbikes.create',compact('classifys'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateMotorbikeRequest $request)
    {
        if($request->has('file_upload')) {
            $file = $request ->file_upload;
            $ext = $request ->file_upload->extension();
            $file_name = rand(1,10000).'-'.'product.'.$ext;
            $file->move(public_path('productImg'),$file_name);
            $request->merge(['image' => $file_name]);
        }
        $request['status'] = 'Còn trống';
        Motorbike::create($request->all());
        Session::flash('statuscode','success');
        return to_route('motorbikes.index')->with(['message'=>'Thêm mới thành công']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $classifys = Classifybike::all();
        $motorbikes = Motorbike::findOrFail($id);
        return view('admin.motorbikes.edit',compact('motorbikes','classifys'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateMotorbikeRequest $request, $id)
    {
        $motorbikes = Motorbike::findOrFail($id);
        if($request->has('file_upload')) {
                unlink('productImg/' .$motorbikes->image);
                $file = $request ->file_upload;
                $ext = $file->extension();
                $file_name = rand(1,10000).'-'.'product.'.$ext;
                $file->move(public_path('productImg'),$file_name);
                $request->merge(['image' => $file_name]);
            }
        $motorbikes->update( $request->all());
        Session::flash('statuscode','success');
        return to_route('motorbikes.index')->with(['message'=>'Cập nhật thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $motorbikes= Motorbike::find($id);
        $destination = 'productImg/' .$motorbikes->image;
        if(file_exists($destination)){
            unlink($destination);
        }
        $motorbikes->delete();
        Session::flash('statuscode','success');
        return to_route('motorbikes.index')->with(['message'=>'Xóa thành công']);
    }

    public function search(Request $request)
    {
        $search = $request->search;
        $motorbikes = Motorbike::where(function($query) use ($search){
            $query->where('id',"$search")
            ->orWhere('tenxe','like',"%$search%")
            ->orWhere('hangxe','like',"%$search%")
            ->orWhere('bienso','like',"%$search%")
            ->orWhere('giathue','like',"%$search%");
        })
        ->orWhereHas('classify',function($query) use($search){
            $query->where('tenphanloai','like',"%$search%");
        })
        ->paginate(5)
        ->appends(['search' => $search]);
        return view('admin.motorbikes.index', compact('motorbikes', 'search'));
    }

}

example-app/resources/views/admin/motorbikes/create.blade.php
@extends('admin.layouts.app')
@section('title','Create motorbikes')
@section('content')
    <div class="card">
        <h1>Thêm xe mới</h1>
        <div>
            <form action="{{ route('motorbikes.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="input-group input-group-static mb-4">
                    <label>Tên xe</label>
                    <input type="text" class="form-control" value="{{ old('tenxe') }}" name="tenxe" placeholder="Tên xe">

                    @error('tenxe')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Hãng xe</label>
                    <input type="text" class="form-control" value="{{ old('hangxe') }}" name="hangxe" placeholder="Hãng xe">

                    @error('hangxe')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Biển số</label>
                    <input type="text" class="form-control" value="{{ old('bienso') }}" name="bienso" placeholder="Biển số">

                    @error('bienso')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Giá thuê</label>
                    <input type="text" class="form-control" value="{{ old('giathue') }}" name="giathue" placeholder="Giá thuê">

                    @error('giathue')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror

                </div>

                {{-- <div class="input-group input-group-static mb-4">
                    <label>Trạng thái</label>
                    <input type="text" class="form-control" value="{{ old('status') }}" name="status" placeholder="Trạng thái">

                    @error('status')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror

                </div> --}}

                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Loại xe</label>
                    <select name="classifybike_id" class="form-control">
                        @foreach ($classifys as $item)
                            <option value="{{ $item->id }}">{{ $item->tenphanloai }}</option>
                        @endforeach
                    </select>

                    @error('classifybike_id')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

              <div class="row">
                <div class="input-group-static col-5 mb-4">
                    <label>Hình ảnh</label>
                    <input type="file" class="form-control" value="{{ old('file_upload') }}" name="file_upload" id="image-input" placeholder="thêm ảnh">

                    @error('file_upload')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror

                </div>
                <div class="col-5">
                    <img src="{{ asset('../productImg/no-image.png')}}" id="show-image" alt="" width="200" height="140">
                </div>
              </div>


                <button type="submit" class="btn btn-submit btn-primary">Thêm mới</button>
            </form>
        </div>
    </div>

@endsection

example-app/resources/views/admin/motorbikes/edit.blade.php
@extends('admin.layouts.app')
@section('title','Edit motorbikes' . $motorbikes->tenxe)
@section('content')
    <div class="card">
        <h1>Chỉnh sửa thông tin xe</h1>
        <div>
            <form action="{{ route('motorbikes.update', $motorbikes->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="input-group input-group-static mb-4">
                    <label>Tên xe</label>
                    <input type="text" class="form-control" value="{{ old('tenxe',$motorbikes->tenxe) }}" name="tenxe" placeholder="Tên xe">

                    @error('tenxe')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Hãng xe</label>
                    <input type="text" class="form-control" value="{{ old('hangxe', $motorbikes->hangxe) }}" name="hangxe" placeholder="Hãng xe">

                    @error('hangxe')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Biển số</label>
                    <input type="text" class="form-control" value="{{ old('bienso', $motorbikes->bienso) }}" name="bienso" placeholder="Biển số">

                    @error('bienso')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Giá</label>
                    <input type="text" class="form-control" value="{{ old('giathue',$motorbikes->giathue) }}" name="giathue" placeholder="Gía">

                    @error('giathue')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Trạng thái</label>
                    <select name="status" class="form-control">
                        <option value="Còn trống" {{ old('status', $motorbikes->status) === 'Còn trống' ? 'selected' : '' }}>Còn trống</option>
                        <option value="Đang bận" {{ old('status', $motorbikes->status) === 'Đang bận' ? 'selected' : '' }}>Đang bận</option>
                    </select>

                    @error('status')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>


                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Loại xe</label>
                    <select name="classifybike_id" class="form-control">
                        {{-- <option value="">{{$motorbikes->classifybike_id}}</option> --}}
                        @foreach ($classifys as $item)
                            <option value="{{ $item->id }}" {{ $motorbikes->classifybike_id == $item->id ? 'selected' : '' }}>{{ $item->tenphanloai }}</option>
                        @endforeach
                    </select>

                    @error('classifybike_id')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="row">
                    <div class="input-group-static col-5 mb-4">
                        <label>Hình ảnh</label>
                        <input type="file" class="form-control" name="file_upload" value="{{ old('file_upload') }}"  id="image-input" placeholder="thêm ảnh">

                        @error('file_upload')
                            <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>
                    <div class="col-5">
                        @if ($motorbikes->image)
                        {{-- <img src="{{ asset('../productImg/'.$motorbikes->image) }}" alt="Current Image" width="200"> --}}
                        <img src="{{ asset('../productImg/'.$motorbikes->image)}}" id="show-image" alt="" width="200" height="140">
                        @endif
                    </div>
                  </div>


                <button type="submit" class="btn btn-submit btn-primary">Cập nhật</button>
            </form>
        </div>
    </div>

@endsection

example-app/resources/views/admin/motorbikes/index.blade.php
@extends('admin.layouts.app')
@section('title', 'motorbikes')
@section('content')
    <div class="card" style="padding: 32px;">

        <h1>
            Danh sách xe
        </h1>

        <div>
            <div class="row">
                <div class="col-md-6">
                    <a href="{{ route('motorbikes.create') }}" class="btn btn-primary"
                        style="background-color:green">Create</a>
                </div>
                <div class="col-md-6">
                    <form method="get" action="{{ route('motorbikes.search') }}">
                        <div class="input-group">
                            <input class="form-control" name="search" placeholder="Search ..." value="{{ $search ?? '' }}"
                                style="
                            border: 1px solid #ccc;
                            padding: 10px;
                            border-top-right-radius: 0 !important;
                            border-bottom-right-radius: 0px !important;">
                            <button type="submit" class="btn btn-primary"
                                style="margin-left: 0px;margin-bottom: 0px;">Search</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="table-responsive">
                <table class= "table table-hover" style="vertical-align: middle; border: 1px solid #134ca1;">
                    <tr class="table-primary">
                        <th>#</th>
                        <th>Tên xe</th>
                        <th>Hãng xe</th>
                        <th>Biển số</th>
                        <th>Giá thuê</th>
                        <th>Loại xe</th>
                        <th>Trạng thái</th>
                        <th>Hình ảnh</th>
                        <th>Hành động</th>
                    </tr>
                    @php
                        $index = 1;
                    @endphp
                    @foreach ($motorbikes as $motorbike)
                        <tr>
                            <td>{{ $index }}</td>
                            <td>{{ $motorbike->tenxe }}</td>
                            <td>{{ $motorbike->hangxe }}</td>
                            <td>{{ $motorbike->bienso }}</td>
                            <td>{{ $motorbike->giathue }}</td>
                            <td>{{ $motorbike->classify->tenphanloai }}</td>
                            <td>{{ $motorbike->status }}</td>
                            <td>
                                <a href="{{ asset('../productImg/' . $motorbike->image) }}" data-fancybox data-caption="Hello">
                                    <img src="{{ asset('../productImg/' . $motorbike->image) }}" alt="" width="200px"
                                        height="120px">
                                </a>
                            </td>
                            <td>
                                <a href="{{ route('motorbikes.edit', $motorbike->id) }}" style="text-decoration: none;">
                                    <i style="color: black;" class="fas fa-pen"></i>
                                </a>

                                <form action="{{ route('motorbikes.destroy', $motorbike->id) }}" id="form-delete{{ $motorbike->id }}"
                                    method="post" class="d-inline" style="margin:0;">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-link btn-delete" data-id={{ $motorbike->id }} style="margin:0;">
                                        <i style="color: red;" class="fas fa-trash"></i></button>
                                </form>

                            </td>
                        </tr>
                        @php
                            $index++;
                        @endphp
                    @endforeach

                </table>
            </div>
            {{ $motorbikes->links() }}
        </div>

    </div>

@endsection
@push('script')
    <script>
        @if (session('message'))
            // alert('{{ session('message') }}');
            Swal.fire({
                position: "top-end",
                icon: '{{ session('statuscode') }}',
                title: '{{ session('message') }}',
                showConfirmButton: false,
                timer: 1500,
            })
        @endif
    </script>
@endpush