example-app/routes/web.php
<?php

use App\Http\Controllers\Admin\BillController;
use App\Http\Controllers\Admin\ClassifyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MotorbikeController;
use App\Http\Controllers\Admin\OrderbikeController;
use App\Models\Classifybike;
use App\Models\Customer;

use App\Http\Controllers\Admin\Motorbikeontroller;
use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard')
->middleware('auth');





// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('roles', RoleController::class);

Route::get('/motorbikes/search', [MotorbikeController::class,'search'])->name('motorbikes.search');
Route::resource('motorbikes', MotorbikeController::class)->middleware('auth');






Route::get('/classify/search', [ClassifyController::class,'search'])->name('classify.search');
Route::resource('classify',ClassifyController::class)->middleware('auth');



// Route::get('customers/create', CustomerController::class, 'create')->name('customers.create');






Auth::routes();







// // Route::resource('orderbikes',OrderbikeController::class);
// //search
// Route::get('/orderbikes/search', [OrderbikeController::class,'search'])->name('orderbikes.search');

// //orderbike
// Route::get('/orderbikes',[OrderbikeController::class, 'index'])
// ->name('orderbikes.index');



// // create orderbike
// Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])
// ->name('orderbikes.create');
// Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])
// ->name('orderbikes.store');
// //show
// Route::get('orderbikes/{id}', [OrderbikeController::class,'show'])
// ->name('orderbikes.show');

// //edit orderbike
// Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])
// ->name('orderbikes.edit');
// Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])
// ->name('orderbikes.update');

// //delete
// Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])
// ->name('orderbikes.destroy');


Route::middleware('auth')->group(function () {
    // Search Orderbikes
    Route::get('/orderbikes/search', [OrderbikeController::class, 'search'])->name('orderbikes.search');

    // Show Orderbikes
    Route::get('/orderbikes', [OrderbikeController::class, 'index'])->name('orderbikes.index');

    // Create Orderbike
    Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])->name('orderbikes.create');
    Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])->name('orderbikes.store');

    // Show Orderbike details
    Route::get('/orderbikes/{id}', [OrderbikeController::class, 'show'])->name('orderbikes.show');

    // Edit Orderbike
    Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])->name('orderbikes.edit');
    Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])->name('orderbikes.update');

    // Delete Orderbike
    Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])->name('orderbikes.destroy');
});





// //customers
// Route::get('/customers',[CustomerController::class, 'index'])
// ->name('customers.index');

// // create customers
// Route::get('/customers/create', [CustomerController::class, 'create'])
// ->name('customers.create');
// Route::post('/customers/store', [CustomerController::class, 'store'])
// ->name('customers.store');

// //edit customers
// Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])
// ->name('customers.edit');
// Route::put('/customers/update/{id}', [CustomerController::class, 'update'])
// ->name('customers.update');

// //delete
// Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])
// ->name('customers.destroy');

// //search
// Route::get('/customers/search', [CustomerController::class,'search'])->name('customers.search');


// Route::post('/customers/store-ajax', [CustomerController::class,'storeAjax'])->name('customers.storeAjax');

Route::middleware('auth')->group(function () {
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers/store', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/update/{id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])->name('customers.destroy');
    Route::get('/customers/search', [CustomerController::class, 'search'])->name('customers.search');
    Route::post('/customers/store-ajax', [CustomerController::class, 'storeAjax'])->name('customers.storeAjax');
});









Route::get('/bills/search', [BillController::class,'search'])->name('bills.search');

Route::resource('bills', BillController::class)->middleware('auth');
Route::post('/bills/store', [BillController::class, 'store'])
->name('bills.store')->middleware('auth');

example-app/app/Models/Orderbike.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Orderbike extends Model
{
    use HasFactory;


    protected $fillable = [
        'ngaybatdauthue',
        'ngaydutra',
        'status',
        'customer_id',
        'motorbike_id',
        'tamung',
        'ghichu'
    ];

    protected $attributes = [
        'tamung' => 0,
    ];

    public function customer(){
        return $this->belongsTo(Customer::class,'customer_id');
    }

    public function orderbike_bike(){

        return $this->belongsTo(Motorbike::class,'motorbike_id');
    }

    // Định nghĩa quan hệ thuộc về hóa đơn (Bill)
    public function bill()
    {
        return $this->hasOne(Bill::class);
    }

}

example-app/app/Http/Controllers/Admin/OrderbikeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Orderbike\CreateOrderRequest;
use App\Http\Requests\Orderbike\UpdateOrderRequest;
use App\Models\Customer;
use App\Models\Motorbike;
use App\Models\Orderbike;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class OrderbikeController extends Controller
{   

    protected $orderbike;

    /**
     * @pram $bike
     */
    public function __construct(Orderbike $orderbike) {
        $this->orderbike = $orderbike;
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {   
        $orderbikes = Orderbike::with('customer','orderbike_bike')
        ->paginate(15);
            // dd($orderbikes);
        return view('admin.orderbike.index',compact('orderbikes'));
        
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {   
        $customers = Customer::all();
        $motorbikes = Motorbike::where('status', 'Còn trống')->get();
        if ($motorbikes->isEmpty()) {
            Session::flash('statuscode','error');
            return redirect()->route('orderbikes.index')->with('message', 'Không còn xe nào đang trống!');
        }
        return view('admin.orderbike.create',compact('customers','motorbikes'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateOrderRequest $request)
    {   
        $orderData = $request->all();
    if ($request->has('action') && $request->input('action') === 'thuexe') {
        $orderData['status'] = 'Đã giao xe';
        $motorbikeId = $orderData['motorbike_id'];
        Motorbike::where('id', $motorbikeId)->update(['status' => 'Đang bận']);
    } else {
        $orderData['status'] = 'Chưa giao xe';
        $motorbikeId = $orderData['motorbike_id'];
        Motorbike::where('id', $motorbikeId)->update(['status' => 'Đang bận']);
    }
    Orderbike::create($orderData);
        // Orderbike::create($request->all());
        
        // $motorbikeId = $request['motorbike_id'];
        // Motorbike::where('id', $motorbikeId)->update(['status' => 'Đang bận']);
        Session::flash('statuscode','success');
        return to_route('orderbikes.index')->with(['message'=>'Cho thuê thành công']);
        
        
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $orderbikes = Orderbike::with('customer', 'orderbike_bike')->findOrFail($id);
        return view('admin.orderbike.show', compact('orderbikes'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {   
        $orderbikes = Orderbike::findOrFail($id);
        $customers = Customer::all();
        // $motorbikes = Motorbike::all();
        $motorbikeOld = Motorbike::findOrFail($orderbikes->orderbike_bike->id);
        $motorbikes = Motorbike::where('motorbikes.status', 'Còn trống')->get();
        return view('admin.orderbike.edit',compact('customers','motorbikes','orderbikes', 'motorbikeOld'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateOrderRequest $request, string $id)
    {   
        // dd(123);
        $data = $request->all();
        // $request['status'] = '123123';
        $orderbikes = Orderbike::findOrFail($id);

        $motorbikeOldId = $orderbikes->motorbike_id;
        $motorbikeNewId = $data['motorbike_id'];

        if ($motorbikeOldId !== $motorbikeNewId) {
            $motorbikeOld = Motorbike::findOrFail($motorbikeOldId);
            $motorbikeOld->update(['status' => 'Còn trống']);
        }

        $motorbikeNew = Motorbike::findOrFail($motorbikeNewId);
        $motorbikeNew->update(['status' => 'Đang bận']);
        // dd($request->all());
        $orderbikes->update($data);

        Session::flash('statuscode','success');
        return to_route('orderbikes.index')->with(['message'=>'Cập nhật thành công']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // Orderbike::destroy($id);
        // return to_route('orderbikes.index')->with(['message'=>'Xóa thành công']);
        $orderbike = Orderbike::findOrFail($id);

        // Check if the order has the status "Chưa giao xe" before allowing deletion
        if ($orderbike->status === 'Chưa giao xe') {
            // Update bike status to "Còn trống"
            $orderbike->orderbike_bike->update(['status' => 'Còn trống']);
    
            // Delete the order
            $orderbike->delete();
            Session::flash('statuscode','success');
            return to_route('orderbikes.index')->with(['message' => 'Xóa thành công']);
        } else {
            Session::flash('statuscode','error');
            return to_route('orderbikes.index')->with(['message' => 'Không thể xóa đơn hàng đã giao xe']);
        }
    }

    public function search(Request $request)
    {
        $search = $request->search;
        $orderbikes = Orderbike::where(function($query) use ($search){
            $query->where('id',"$search")
            ->orWhere('status','like',"%$search%")
            ->orWhere('ngaybatdauthue','like',"%$search%")
            ->orWhere('ngaydutra','like',"%$search%");
        })
        ->orWhereHas('customer',function($query) use($search){
            $query->where('hoten','like',"%$search%");
        })
        ->orWhereHas('orderbike_bike',function($query) use($search){
            $query->where('tenxe','like',"%$search%")
            ->orWhere('bienso','like',"%$search%")
            ->orWhere('giathue','like',"%$search%");
        })
        ->paginate(5)
        ->appends(['search' => $search]);
        return view('admin.orderbike.index', compact('orderbikes', 'search'));
    }
}

example-app/resources/views/admin/orderbike/create.blade.php
@extends('admin.layouts.app')
@section('title','Create Orderbikes')
@section('content')
    <div class="card" style="padding: 32px;">
        <h1>Cho thuê</h1>
        <div>
            <form action="{{ route('orderbikes.store')}}" method="POST">
                @csrf
                <div class="input-group input-group-static mb-4">
                    <label name = "group" class="ms-0">Họ và tên khách hàng</label>
                    <select name="customer_id" class="form-control">
                        @foreach ($customers as $customer)
                        <option value={{ $customer->id }}>{{ $customer->hoten }}</option>
                        @endforeach

                        @error('customer_id')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror
                    </select>

                </div>

                <div class="input-group input-group-static mb-4">
                    <label name = "group" class="ms-0">Chọn xe</label>
                    <select name="motorbike_id" class="form-control">
                        @foreach ($motorbikes as $motorbike)
                        <option value="{{ $motorbike->id}}">{{ $motorbike->tenxe }} - {{ $motorbike->bienso }} - {{ $motorbike->status }}</option>
                        
                        @endforeach
                    </select>
                </div>



                <div class="input-group input-group-static mb-4">
                    <label>Ngày bắt đầu thuê</label>
                    <input type="datetime-local" class="form-control" value="{{ old('ngaybatdauthue') }}" name="ngaybatdauthue" placeholder="Ngày bắt đầu thuê">

                    @error('ngaybatdauthue')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Ngày dự kiến trả</label>
                    <input type="datetime-local" class="form-control" value="{{ old('ngaydutra') }}" name="ngaydutra" placeholder="Ngày dự kiến trả">

                    @error('ngaydutra')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Tạm ứng</label>
                    <input type="text" class="form-control" value="{{ old('tamung','0') }}" name="tamung" placeholder="">

                    @error('tamung')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Ghi chú</label>
                    <input type="text" class="form-control" value="{{ old('ghichu') }}" name="ghichu" placeholder="Ghi chú">

                    @error('ghichu')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <button type="submit" name="action" value="khonggiao" class="btn btn-submit btn-primary">Thêm mới</button>
                <button type="submit" name="action" value="thuexe" class="btn btn-submit btn-primary">Thêm mới và giao xe</button>
            </form>
        </div>
    </div>
    
@endsection

example-app/resources/views/admin/orderbike/edit.blade.php
@extends('admin.layouts.app')
@section('title','Edit Orderbikes')
@section('content')
    <div class="card">
        <h1>Chỉnh sửa thông tin đặt xe</h1>
        <div>
            <form action="{{ route('orderbikes.update', $orderbikes->id) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="input-group input-group-static mb-4">
                    <label name = "group" class="ms-0">Họ và tên khách hàng</label>
                    <select name="customer_id" class="form-control">
                        @foreach ($customers as $customer)
                        <option value={{ $customer->id }} {{ old('customer_id', $orderbikes->customer_id) == $customer->id ? 'selected' : '' }}>{{ $customer->hoten }}</option>
                        @endforeach

                        @error('customer_id')
                        <span class="text-danger"> {{ $message}}</span>
                        @enderror
                    </select>
                </div>

                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Chọn xe</label>
                    <select name="motorbike_id" class="form-control">
                        @if ($motorbikeOld->id == old('motorbike_id', $orderbikes->motorbike_id))
                            <option value={{ $motorbikeOld->id }}>{{ $motorbikeOld->tenxe }} - {{ $motorbikeOld->bienso }} - {{ $motorbikeOld->status }}</option>
                        @endif
                        @foreach ($motorbikes as $motorbike)
                            <option value="{{ $motorbike->id }}" {{$motorbike->id == $orderbikes->motorbike_id ? 'selected' : '' }}>
                                {{ $motorbike->tenxe }} - {{ $motorbike->bienso }} - {{ $motorbike->status }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Ngày bắt đầu thuê</label>
                    <input type="datetime-local" class="form-control" value="{{ old('ngaybatdauthue', $orderbikes->ngaybatdauthue) }}" 
                            name="ngaybatdauthue">

                    @error('ngaybatdauthue')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Ngày dự trả</label>
                    <input type="datetime-local" class="form-control" value="{{ old('ngaydutra', $orderbikes->ngaydutra) }}" 
                            name="ngaydutra">

                    @error('ngaydutra')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Tạm ứng</label>
                    <input type="text" class="form-control" value="{{ old('tamung',$orderbikes->tamung) }}" name="tamung" placeholder="0">

                    @error('tamung')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Ghi chú</label>
                    <input type="text" class="form-control" value="{{ old('ghichu',$orderbikes->ghichu) }}" name="ghichu" placeholder="Ghi chú">

                    @error('ghichu')
                        <span class="text-danger"> {{ $message}}</span>
                    @enderror

                </div>
                <div class="input-group input-group-static mb-4">
                    <label>Trạng thái</label>
                    <select name="status" class="form-control">
                        <option value="Đã giao xe" {{ old('status', $orderbikes->status) === 'Đã giao xe' ? 'selected' : '' }}>Đã giao xe</option>
                        <option value="Chưa giao xe" {{ old('status', $orderbikes->status) === 'Chưa giao xe' ? 'selected' : '' }}>Chưa giao xe</option>
                    </select>
                
                    @error('status')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Cập nhật</button>
            </form>
        </div>
    </div>
    
@endsection

example-app/resources/views/admin/orderbike/index.blade.php
@extends('admin.layouts.app')
@section('title','Orderbikes')
@section('content')
    <div class="card" style="padding: 32px;">

        <h1>
            Đặt xe
        </h1>

        <div>
            <div class="row">
                <div>
                    <!-- Trigger the modal -->
                    <button type="button" class="btn btn-primary" style="background-color:dodgerblue" data-bs-toggle="modal"
                     data-bs-target="#addCustomerModal">
                     Thêm khách hàng mới
                    </button>
                </div>

                <div class="col-md-6">
                    <a href="{{ route('orderbikes.create') }}" class="btn btn-primary" style="background-color:green">Create</a>
                </div>

                <div class="col-md-6">
                    <form method="get" action="{{ route('orderbikes.search') }}">
                        <div class="input-group">
                            <input class="form-control" name="search" placeholder="Search ..."
                            style="
                            border: 1px solid #ccc;
                            padding: 10px;
                            border-top-right-radius: 0 !important;
                            border-bottom-right-radius: 0px !important;"
                            value="{{ $search ?? '' }}">
                            <button type="submit" class="btn btn-primary" style="margin-left: 0px;margin-bottom: 0px;">Search</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="table-responsive">
                <table class= "table table-hover" style="vertical-align: middle; border: 1px solid #134ca1;">
                    <tr class="table-primary">
                        <th>STT</th>
                        <th>Tên khách hàng</th>
                        <th>Tên xe</th>
                        <th>Biển số</th>
                        <th>Giá thuê</th>
                        <th>Ngày bắt đầu thuê</th>
                        <th>Ngày dự kiến trả</th>
                        <th>Trạng thái</th>
                        <th>Hành động</th>
                    </tr>
                    @php
                        $index = 1;
                    @endphp
                    @foreach ($orderbikes as $orderbike)
                    <tr>
                        <td>{{ $index }}</td>
                        <td>{{ $orderbike->customer->hoten}}</td>
                        <td>{{ $orderbike->orderbike_bike->tenxe}}</td>
                        <td>{{ $orderbike->orderbike_bike->bienso }}</td>
                        <td>{{ $orderbike->orderbike_bike->giathue }}</td>
                        <td>{{ $orderbike->ngaybatdauthue }}</td>
                        <td>{{ $orderbike->ngaydutra }}</td>
                        <td>{{ $orderbike->status }}</td>
                        <td >
                            @if ($orderbike->status != 'Đã thanh toán') <!-- Kiểm tra trạng thái -->
                            <a href="{{ route('orderbikes.edit', $orderbike->id) }}" style="text-decoration: none;">
                                <i style="color: black;" class="fas fa-pen"></i>
                            </a>
                            <form action="{{ route('orderbikes.destroy', $orderbike->id) }}" id="form-delete{{ $orderbike->id }}"
                                method="post" style="margin: 0;" class="d-inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-link btn-delete" style="margin: 0;" data-id={{ $orderbike->id }}>
                                    <i class="fas fa-trash" style="color: red;"></i>
                                </button>
                            </form>
                            <a href="{{ route('orderbikes.show', $orderbike->id) }}" style="text-decoration: none;">
                                <i style="color:black;" class="fas fa-eye"></i>
                            </a>
                            @endif

                            @if ($orderbike->status == 'Đã giao xe') <!-- Kiểm tra trạng thái -->
                            <a href="{{ route('bills.create', ['orderbike' => $orderbike->id, 'tamung' => $orderbike->tamung, 'ngaybatdauthue' => $orderbike->ngaybatdauthue]) }}" >
                                {{-- class="btn btn-primary" style="margin: 0;">Pay</a> --}}
                                <i class="fas fa-credit-card"  style="margin-left: 10px;"></i></a>
                            @endif
                        </td>
                    </tr>
                    @php
                        $index++;
                    @endphp
                    @endforeach
               </table>
                {{ $orderbikes->links() }}
            </div>
        </div>
        @Include('admin.orderbike.modal')
    </div>
@endsection
@push('script')
 <!-- Include jQuery (if not already included) -->
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
 <!-- Include custom.js -->
 <script src="{{ asset('admin/assets/js/custom.js') }}"></script>
<script>
    @if (session('message'))
             // alert('{{session('message') }}');
             Swal.fire({
                 position: "top-end",
                 icon: '{{session('statuscode') }}',
                 title: '{{session('message') }}',
                 showConfirmButton: false,
                 timer: 1500,
             })

     @endif

 </script>
@endpush

example-app/resources/views/admin/orderbike/modal.blade.php
<div class="modal fade" id="addCustomerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Thêm khách hàng mới </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <form id="addCustomerForm" action="{{ route('customers.storeAjax') }}" method="POST" enctype="multipart/form-data" >
                @csrf
                <div class="modal-body">
                    <div class="input-group input-group-static mb-4">
                        <label>Họ và tên</label>
                        <input type="text" class="form-control" value="{{ old('hoten') }}" name="hoten" placeholder="Họ và tên">
                        <span class="text-danger"></span>
    
                        @error('hoten')
                            <span class="text-danger"> {{ $message}}</span>
                        @enderror
    
                    </div>
    
                    <div class="input-group input-group-static mb-4">
                        <label>Số điện thoại</label>
                        <input type="text" class="form-control" value="{{ old('sdt') }}" name="sdt" placeholder="Số điện thoại">
                        <span class="text-danger"></span>
    
                        @error('sdt')
                            <span class="text-danger"> {{ $message}}</span>
                        @enderror
    
                    </div>
                    
                    <div class="input-group input-group-static mb-4">
                        <label>Căn cước công dân</label>
                        <input type="text" class="form-control" value="{{ old('cccd') }}" name="cccd" placeholder="Căn cước công dân">
                        <span class="text-danger"></span>
    
                        @error('cccd')
                            <span class="text-danger"> {{ $message}}</span>
                        @enderror
    
                    </div>
    
                    <div class="input-group input-group-static mb-4">
                        <label>Bằng lái</label>
                        <input type="text" class="form-control" value="{{ old('banglai') }}" name="banglai" placeholder="Bằng lái">
                        <span class="text-danger"></span>
    
                        @error('banglai')
                            <span class="text-danger"> {{ $message}}</span>
                        @enderror
    
                    </div>
                    
                    <div class="row">
                        <div class="input-group-static col-5 mb-4">
                            <label>Ảnh mặt trước</label>
                            <input type="file" class="form-control" value="{{ old('cccd1') }}" name="cccd1" id="image-input" placeholder="thêm ảnh">
                            <span class="text-danger"></span>
        
                            @error('cccd1')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-5">
                            <img src="{{ asset('../imagecustomers/no-image.png')}}" id="show-image" alt="" width="200" height="140">
                        </div>
                  </div>
    
    
                    <div class="row">
                        <div class="input-group-static col-5 mb-4">
                            <label>Ảnh mặt sau</label>
                            <input type="file" class="form-control" value="{{ old('cccd2') }}" name="cccd2" id="image-input1" placeholder="thêm ảnh">
                            <span class="text-danger"></span>
        
                            @error('cccd2')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-5">
                            <img src="{{ asset('../imagecustomers/no-image.png')}}" id="show-image1" alt="" width="200" height="140">
                        </div>
                    </div>
    
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary" id="addCustomerBtn">Thêm mới</button>

                </div>
            </form>
      </div>
    </div>
  </div>