example-app/routes/web.php
<?php

use App\Http\Controllers\Admin\BillController;
use App\Http\Controllers\Admin\ClassifyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MotorbikeController;
use App\Http\Controllers\Admin\OrderbikeController;
use App\Models\Classifybike;
use App\Models\Customer;

use App\Http\Controllers\Admin\Motorbikeontroller;
use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard')
->middleware('auth');





// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('roles', RoleController::class);

Route::get('/motorbikes/search', [MotorbikeController::class,'search'])->name('motorbikes.search');
Route::resource('motorbikes', MotorbikeController::class)->middleware('auth');






Route::get('/classify/search', [ClassifyController::class,'search'])->name('classify.search');
Route::resource('classify',ClassifyController::class)->middleware('auth');



// Route::get('customers/create', CustomerController::class, 'create')->name('customers.create');






Auth::routes();







// // Route::resource('orderbikes',OrderbikeController::class);
// //search
// Route::get('/orderbikes/search', [OrderbikeController::class,'search'])->name('orderbikes.search');

// //orderbike
// Route::get('/orderbikes',[OrderbikeController::class, 'index'])
// ->name('orderbikes.index');



// // create orderbike
// Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])
// ->name('orderbikes.create');
// Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])
// ->name('orderbikes.store');
// //show
// Route::get('orderbikes/{id}', [OrderbikeController::class,'show'])
// ->name('orderbikes.show');

// //edit orderbike
// Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])
// ->name('orderbikes.edit');
// Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])
// ->name('orderbikes.update');

// //delete
// Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])
// ->name('orderbikes.destroy');


Route::middleware('auth')->group(function () {
    // Search Orderbikes
    Route::get('/orderbikes/search', [OrderbikeController::class, 'search'])->name('orderbikes.search');

    // Show Orderbikes
    Route::get('/orderbikes', [OrderbikeController::class, 'index'])->name('orderbikes.index');

    // Create Orderbike
    Route::get('/orderbikes/create', [OrderbikeController::class, 'create'])->name('orderbikes.create');
    Route::post('/orderbikes/store', [OrderbikeController::class, 'store'])->name('orderbikes.store');

    // Show Orderbike details
    Route::get('/orderbikes/{id}', [OrderbikeController::class, 'show'])->name('orderbikes.show');

    // Edit Orderbike
    Route::get('/orderbikes/edit/{id}', [OrderbikeController::class, 'edit'])->name('orderbikes.edit');
    Route::put('/orderbikes/update/{id}', [OrderbikeController::class, 'update'])->name('orderbikes.update');

    // Delete Orderbike
    Route::delete('/orderbikes/delete/{id}', [OrderbikeController::class, 'destroy'])->name('orderbikes.destroy');
});





// //customers
// Route::get('/customers',[CustomerController::class, 'index'])
// ->name('customers.index');

// // create customers
// Route::get('/customers/create', [CustomerController::class, 'create'])
// ->name('customers.create');
// Route::post('/customers/store', [CustomerController::class, 'store'])
// ->name('customers.store');

// //edit customers
// Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])
// ->name('customers.edit');
// Route::put('/customers/update/{id}', [CustomerController::class, 'update'])
// ->name('customers.update');

// //delete
// Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])
// ->name('customers.destroy');

// //search
// Route::get('/customers/search', [CustomerController::class,'search'])->name('customers.search');


// Route::post('/customers/store-ajax', [CustomerController::class,'storeAjax'])->name('customers.storeAjax');

Route::middleware('auth')->group(function () {
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers/store', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/edit/{id}', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/update/{id}', [CustomerController::class, 'update'])->name('customers.update');
    Route::delete('/customers/delete/{id}', [CustomerController::class, 'destroy'])->name('customers.destroy');
    Route::get('/customers/search', [CustomerController::class, 'search'])->name('customers.search');
    Route::post('/customers/store-ajax', [CustomerController::class, 'storeAjax'])->name('customers.storeAjax');
});









Route::get('/bills/search', [BillController::class,'search'])->name('bills.search');

Route::resource('bills', BillController::class)->middleware('auth');
Route::post('/bills/store', [BillController::class, 'store'])
->name('bills.store')->middleware('auth');

example-app/app/Models/Classifybike.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Classifybike extends Model
{
    use HasFactory;

    protected $fillable = [
        'tenphanloai'
    ];

    public function motorbikes(){

        return $this->hasMany(Motorbike::class);
    }
}

example-app/resources/views/admin/classifybike/create.blade.php
@extends('admin.layouts.app')
@section('title', 'create classify')
@section('content')
    <div class="card">
        <h1>Thêm Mới</h1>
        <div>
            <form action="{{route('classify.store')}}" method="POST">
                @csrf
    
                <div class="input-group input-group-static mb-4">
                    <label>Tên phân loại</label>
                        <input type="text" value="{{ old('tenphanloai') }}" name="tenphanloai" class="form-control">
    
                        @error('tenphanloai')
                            <span class="text-danger"> {{ $message }}</span>
                        @enderror
                </div>
        </div>

            <button type="submit" class="btn btn-submit btn-primary">Thêm mới</button>
        </form>
    </div>

@endsection

example-app/resources/views/admin/classifybike/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'edit classify'. $classifys->tenphanloai)
@section('content')
    <div class="card">
        <h1>Chỉnh sửa</h1>
    </div>

    <div></div>
        <form action="{{route('classify.update', $classifys->id)}}" method="POST">
            @csrf
            @method('PUT')
            <div class="input-group input-group-static mb-4">
                <label>Tên phân loại</label>
                    <input type="text" value="{{ old('tenphanloai') }}" name="tenphanloai" class="form-control">

                    @error('tenphanloai')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
            </div>
            <button type="submit" class="btn btn-submit btn-primary">Cập nhập</button>
        </form>
    </div>

@endsection

example-app/resources/views/admin/classifybike/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Classifybikes')
@section('content')
    <div class="card">

        <h1>
            Danh sách phân loại xe
        </h1>

        <div>
            <a href="{{ route('classify.create') }}" class="btn btn-primary" style="background-color:green">Create</a>
        </div>

        <div class="table-responsive">
            <table class="table table-hover" style="vertical-align: middle; border: 1px solid #134ca1;">
                <tr class="table-primary">
                    <th>STT</th>
                    <th>Tên phân loại</th>
                    <th>Hành động</th>
                </tr>
                @php
                    $index = 1;
                @endphp
                @foreach ($classifys as $classify)
                    <tr>
                        <td>{{ $index }}</td>
                        <td>{{ $classify->tenphanloai }}</td>
                        <td>
                            <a href="{{ route('classify.edit', $classify->id) }}" style="text-decoration: none;">
                                <i style="color: black;" class="fas fa-pen"></i>
                            </a>

                            <form action="{{ route('classify.destroy', $classify->id) }}"
                                id="form-delete{{ $classify->id }}" method="post" style="margin: 0;" class="d-inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-link btn-delete" data-id={{ $classify->id }} style="margin: 0;">
                                    <i class="fas fa-trash" style="color: red;"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @php
                        $index++;
                    @endphp
                @endforeach

            </table>
            {{ $classifys->links() }}
        </div>
    </div>
@endsection

@push('script')
    <script>
        @if (session('message'))
            // alert('{{ session('message') }}');
            Swal.fire({
                position: "top-end",
                icon: '{{ session('statuscode') }}',
                title: '{{ session('message') }}',
                showConfirmButton: false,
                timer: 1500,
            })
        @endif
    </script>
@endpush